-- -------------------------------------------------------------
-- 

-- File Name: C:\Users\z68j959\Documents\GitHub\EELE466\hdl_coder_Madgwick_correction\codegen\Madgwick_correction\hdlsrc\Madgwick_correction_fixpt_pac.vhd
-- Created: 2015-03-31 12:39:01
-- 
-- Generated by MATLAB 8.3, MATLAB Coder 2.6 and HDL Coder 3.4
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Madgwick_correction_fixpt_pac IS
  TYPE vector_of_std_logic_vector14 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(13 DOWNTO 0);
  TYPE vector_of_unsigned14 IS ARRAY (NATURAL RANGE <>) OF unsigned(13 DOWNTO 0);
  TYPE vector_of_std_logic_vector28 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(27 DOWNTO 0);
  TYPE vector_of_unsigned28 IS ARRAY (NATURAL RANGE <>) OF unsigned(27 DOWNTO 0);
  TYPE vector_of_std_logic_vector16 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(15 DOWNTO 0);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE vector_of_std_logic_vector30 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(29 DOWNTO 0);
  TYPE vector_of_unsigned30 IS ARRAY (NATURAL RANGE <>) OF unsigned(29 DOWNTO 0);
  TYPE vector_of_std_logic_vector42 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(41 DOWNTO 0);
  TYPE vector_of_unsigned42 IS ARRAY (NATURAL RANGE <>) OF unsigned(41 DOWNTO 0);
  TYPE vector_of_std_logic_vector19 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(18 DOWNTO 0);
  TYPE vector_of_signed19 IS ARRAY (NATURAL RANGE <>) OF signed(18 DOWNTO 0);
  TYPE vector_of_std_logic_vector33 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(32 DOWNTO 0);
  TYPE vector_of_signed33 IS ARRAY (NATURAL RANGE <>) OF signed(32 DOWNTO 0);
  TYPE vector_of_std_logic_vector15 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(14 DOWNTO 0);
  TYPE vector_of_signed15 IS ARRAY (NATURAL RANGE <>) OF signed(14 DOWNTO 0);
  TYPE vector_of_std_logic_vector34 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(33 DOWNTO 0);
  TYPE vector_of_signed34 IS ARRAY (NATURAL RANGE <>) OF signed(33 DOWNTO 0);
  TYPE vector_of_std_logic_vector17 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(16 DOWNTO 0);
  TYPE vector_of_unsigned17 IS ARRAY (NATURAL RANGE <>) OF unsigned(16 DOWNTO 0);
  TYPE vector_of_std_logic_vector36 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(35 DOWNTO 0);
  TYPE vector_of_signed36 IS ARRAY (NATURAL RANGE <>) OF signed(35 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_signed28 IS ARRAY (NATURAL RANGE <>) OF signed(27 DOWNTO 0);
  TYPE vector_of_signed17 IS ARRAY (NATURAL RANGE <>) OF signed(16 DOWNTO 0);
  TYPE vector_of_std_logic_vector31 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(30 DOWNTO 0);
  TYPE vector_of_signed31 IS ARRAY (NATURAL RANGE <>) OF signed(30 DOWNTO 0);
  TYPE vector_of_unsigned15 IS ARRAY (NATURAL RANGE <>) OF unsigned(14 DOWNTO 0);
  TYPE vector_of_std_logic_vector29 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(28 DOWNTO 0);
  TYPE vector_of_signed29 IS ARRAY (NATURAL RANGE <>) OF signed(28 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_signed30 IS ARRAY (NATURAL RANGE <>) OF signed(29 DOWNTO 0);
  TYPE vector_of_unsigned29 IS ARRAY (NATURAL RANGE <>) OF unsigned(28 DOWNTO 0);
  TYPE vector_of_std_logic_vector62 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(61 DOWNTO 0);
  TYPE vector_of_signed62 IS ARRAY (NATURAL RANGE <>) OF signed(61 DOWNTO 0);
  TYPE vector_of_std_logic_vector65 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(64 DOWNTO 0);
  TYPE vector_of_signed65 IS ARRAY (NATURAL RANGE <>) OF signed(64 DOWNTO 0);
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_std_logic_vector63 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(62 DOWNTO 0);
  TYPE vector_of_signed63 IS ARRAY (NATURAL RANGE <>) OF signed(62 DOWNTO 0);
  TYPE vector_of_std_logic_vector61 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(60 DOWNTO 0);
  TYPE vector_of_signed61 IS ARRAY (NATURAL RANGE <>) OF signed(60 DOWNTO 0);
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE vector_of_signed35 IS ARRAY (NATURAL RANGE <>) OF signed(34 DOWNTO 0);
  TYPE vector_of_signed64 IS ARRAY (NATURAL RANGE <>) OF signed(63 DOWNTO 0);
END Madgwick_correction_fixpt_pac;

