vlib work
vcom  Madgwick_correction_fixpt_pac.vhd
vcom  mux1_serializer.vhd
vcom  alpha0_deserializer.vhd
vcom  mux1_serializer_block.vhd
vcom  alpha0_deserializer_block.vhd
vcom  mux1_serializer_block1.vhd
vcom  alpha0_deserializer_block1.vhd
vcom  mux1_serializer_block2.vhd
vcom  mux1_serializer_block3.vhd
vcom  alpha0_deserializer_block2.vhd
vcom  alpha0_deserializer_block3.vhd
vcom  mux1_serializer_block4.vhd
vcom  alpha0_deserializer_block4.vhd
vcom  mux1_serializer_block5.vhd
vcom  mux1_serializer_block6.vhd
vcom  alpha0_deserializer_block5.vhd
vcom  mux1_serializer_block7.vhd
vcom  alpha0_deserializer_block6.vhd
vcom  mux1_serializer_block8.vhd
vcom  mux1_serializer_block9.vhd
vcom  alpha0_deserializer_block7.vhd
vcom  mux1_serializer_block10.vhd
vcom  alpha0_deserializer_block8.vhd
vcom  mux1_serializer_block11.vhd
vcom  alpha0_deserializer_block9.vhd
vcom  mux1_serializer_block12.vhd
vcom  alpha0_deserializer_block10.vhd
vcom  mux1_serializer_block13.vhd
vcom  mux1_serializer_block14.vhd
vcom  alpha0_deserializer_block11.vhd
vcom  mux1_serializer_block15.vhd
vcom  alpha0_deserializer_block12.vhd
vcom  alpha0_deserializer_block13.vhd
vcom  mux1_serializer_block16.vhd
vcom  alpha0_deserializer_block14.vhd
vcom  mux1_serializer_block17.vhd
vcom  alpha0_deserializer_block15.vhd
vcom  mux1_serializer_block18.vhd
vcom  alpha0_deserializer_block16.vhd
vcom  alpha0_deserializer_block17.vhd
vcom  alpha0_deserializer_block18.vhd
vcom  alpha0_deserializer_block19.vhd
vcom  mux1_serializer_block19.vhd
vcom  alpha0_deserializer_block20.vhd
vcom  mux1_serializer_block20.vhd
vcom  alpha0_deserializer_block21.vhd
vcom  mux1_serializer_block21.vhd
vcom  alpha0_deserializer_block22.vhd
vcom  mux1_serializer_block22.vhd
vcom  mux1_serializer_block23.vhd
vcom  alpha0_deserializer_block23.vhd
vcom  mux1_serializer_block24.vhd
vcom  alpha0_deserializer_block24.vhd
vcom  mux1_serializer_block25.vhd
vcom  mux1_serializer_block26.vhd
vcom  alpha0_deserializer_block25.vhd
vcom  mux1_serializer_block27.vhd
vcom  mux1_serializer_block28.vhd
vcom  alpha0_deserializer_block26.vhd
vcom  mux1_serializer_block29.vhd
vcom  alpha0_deserializer_block27.vhd
vcom  Madgwick_correction_fixpt_tc.vhd
vcom  Madgwick_correction_fixpt_en.vhd
vcom  Madgwick_correction_fixpt.vhd
