vlib work
vcom  Madgwick_qDot_fixpt_pac.vhd
vcom  mux1_serializer.vhd
vcom  mux1_serializer_block.vhd
vcom  alpha0_deserializer.vhd
vcom  mux1_serializer_block1.vhd
vcom  mux1_serializer_block2.vhd
vcom  alpha0_deserializer_block.vhd
vcom  Madgwick_qDot_fixpt_tc.vhd
vcom  Madgwick_qDot_fixpt_enb_bypa.vhd
vcom  Madgwick_qDot_fixpt.vhd
