-- -------------------------------------------------------------
-- 

-- File Name: C:\Users\z68j959\Documents\GitHub\EELE466\hdl_coder_Madgwick_qDot\codegen\Madgwick_qDot\hdlsrc\mux1_serializer_block1.vhd
-- Created: 2015-03-31 12:40:13
-- 
-- Generated by MATLAB 8.3, MATLAB Coder 2.6 and HDL Coder 3.4
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mux1_serializer_block1
-- Source Path: 
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Madgwick_qDot_fixpt_pac.ALL;

ENTITY mux1_serializer_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_1                         :   IN    std_logic;
        enb_1_1_1                         :   IN    std_logic;
        enb                               :   IN    std_logic;
        in0                               :   IN    vector_of_std_logic_vector14(0 TO 2);  -- ufix14_En14 [3]
        out0                              :   OUT   std_logic_vector(13 DOWNTO 0)  -- ufix14_En14
        );
END mux1_serializer_block1;


ARCHITECTURE rtl OF mux1_serializer_block1 IS

  -- Signals
  SIGNAL in0_unsigned                     : vector_of_unsigned14(0 TO 2);  -- ufix14_En14 [3]
  SIGNAL serial_in                        : vector_of_unsigned14(0 TO 2);  -- ufix14_En14 [3]
  SIGNAL mux1_serializer_bypass_regrsvd   : std_logic;  -- ufix1
  SIGNAL in_vld                           : std_logic;
  SIGNAL mux1_serializer_data             : vector_of_unsigned14(0 TO 2);  -- ufix14 [3]
  SIGNAL mux1_serializer_data_next        : vector_of_unsigned14(0 TO 2);  -- ufix14_En14 [3]
  SIGNAL s_s                              : unsigned(13 DOWNTO 0);  -- ufix14_En14

BEGIN
  outputgen: FOR kk IN 0 TO 2 GENERATE
    in0_unsigned(kk) <= unsigned(in0(kk));
  END GENERATE;

  serial_in <= in0_unsigned;

  mux1_serializer_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mux1_serializer_bypass_regrsvd <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_1_1 = '1' THEN
        mux1_serializer_bypass_regrsvd <= enb_1_4_1;
      END IF;
    END IF;
  END PROCESS mux1_serializer_bypass_process;

  
  in_vld <= enb_1_4_1 WHEN enb_1_1_1 = '1' ELSE
      mux1_serializer_bypass_regrsvd;

  mux1_serializer_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mux1_serializer_data <= (OTHERS => to_unsigned(2#00000000000000#, 14));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        mux1_serializer_data <= mux1_serializer_data_next;
      END IF;
    END IF;
  END PROCESS mux1_serializer_process;

  mux1_serializer_output : PROCESS (mux1_serializer_data, serial_in, in_vld)
    VARIABLE tempv : vector_of_unsigned14(0 TO 1);
  BEGIN
    mux1_serializer_data_next <= mux1_serializer_data;
    IF in_vld /= '0' THEN 
      s_s <= serial_in(0);
    ELSE 
      s_s <= mux1_serializer_data(0);
    END IF;
    IF in_vld /= '0' THEN 
      tempv := serial_in(1 TO 2);
    ELSE 
      tempv := mux1_serializer_data(1 TO 2);
    END IF;
    mux1_serializer_data_next(0 TO 1) <= tempv;
    mux1_serializer_data_next(2) <= serial_in(2);
  END PROCESS mux1_serializer_output;


  out0 <= std_logic_vector(s_s);

END rtl;

