%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.3, MATLAB Coder 2.6 and HDL Coder 3.4        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [s0,s1,s2,s3] = Madgwick_correction_wrapper_fixpt(q0,q1,q2,q3,ax,ay,az,mx,my,mz)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128 );
    q0_in = fi( q0, 0, 14, 14, fm );
    q1_in = fi( q1, 0, 14, 14, fm );
    q2_in = fi( q2, 0, 14, 14, fm );
    q3_in = fi( q3, 0, 14, 14, fm );
    ax_in = fi( ax, 0, 14, 14, fm );
    ay_in = fi( ay, 0, 14, 14, fm );
    az_in = fi( az, 0, 14, 14, fm );
    mx_in = fi( mx, 0, 14, 14, fm );
    my_in = fi( my, 0, 14, 14, fm );
    mz_in = fi( mz, 0, 14, 14, fm );
    [s0_out,s1_out,s2_out,s3_out] = Madgwick_correction_fixpt( q0_in, q1_in, q2_in, q3_in, ax_in, ay_in, az_in, mx_in, my_in, mz_in );
    s0 = double( s0_out );
    s1 = double( s1_out );
    s2 = double( s2_out );
    s3 = double( s3_out );
end
