# Create design library
vlib work
# Create and open project
project new . compile_project
project open compile_project
# Add source files to project
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_segments.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block1.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block2.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block3.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block4.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block5.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block6.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block7.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block8.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block9.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block10.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block11.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block12.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block13.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block14.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block15.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block16.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block17.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block18.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block19.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block20.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block21.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block22.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block23.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block24.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block25.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block26.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block27.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/alpha0_deserializer_block28.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/Madgwick_correction_fixpt.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/Madgwick_correction_fixpt_en.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/Madgwick_correction_fixpt_pac.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/Madgwick_correction_fixpt_tc.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block1.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block2.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block3.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block4.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block5.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block6.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block7.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block8.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block9.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block10.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block11.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block12.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block13.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block14.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block15.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block16.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block17.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block18.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block19.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block20.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block21.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block22.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block23.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block24.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block25.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block26.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block27.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block28.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_correction/mux1_serializer_block29.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_normalize/Madgwick_normalize_fixpt.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_normalize/Madgwick_normalize_fixpt_pac.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/alpha0_deserializer.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/alpha0_deserializer_block.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/Madgwick_qDot_fixpt.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/Madgwick_qDot_fixpt_enb_bypa.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/Madgwick_qDot_fixpt_pac.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/Madgwick_qDot_fixpt_tc.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/mux1_serializer.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_qDot/mux1_serializer_block.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_update/alpha0_deserializer.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_update/Madgwick_update_fixpt.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_update/Madgwick_update_fixpt_enb_by.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_update/Madgwick_update_fixpt_pac.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_update/Madgwick_update_fixpt_tc.vhd"
project addfile "C:/Users/z68j959/Documents/GitHub/EELE466/Madgwick_verification/Madgwick_update/mux1_serializer.vhd"
# Calculate compilation order
project calculateorder
set compcmd [project compileall -n]
# Close project
project close
# Compile all files and report error
if [catch {eval $compcmd}] {
    exit -code 1
}
